org.gradle.jvmargs=-Xmx2G
org.gradle.parallel=false

mod_version=0.1.8
maven_group=ru.feytox
archives_name=etherology

minecraft_version_1_20_1=1.20.1
java_version_1_20_1=17
yarn_mappings_1_20_1=1.20.1+build.10

architectury_api_version_1_20_1=9.2.14
fabric_loader_version_1_20_1=0.17.3
fabric_api_version_1_20_1=0.92.6+1.20.1
forge_version_1_20_1=1.20.1-47.4.9

lombok_version_1_20_1=1.18.36
owo_lib_version_1_20_1=0.11.2+1.20
cardinal_components_version_1_20_1=5.2.3
trinkets_version_1_20_1=3.7.2
geckolib_version_1_20_1=4.8.4
geckolib_forge_version_1_20_1=4.7.4
fabric_shield_lib_version_1_20_1=1.7.2-1.20.1
midnightlib_version_1_20_1=1.4.1-fabric
biolith_version_1_20_1=1.0.1-alpha.1
mixin_squared_version_1_20_1=0.2.0
fabric_asm_version_1_20_1=v2.3
mixin_extras_version_1_20_1=0.5.0

cloth_config_version_1_20_1=11.1.136
mod_menu_version_1_20_1=7.2.2
rei_version_1_20_1=12.1.785
emi_version_1_20_1=1.1.24+1.20.1
